name: Slimy
description: Slimy
author: FearMig
website: www.github.com/fearmig
version: 1.0
main: org.mig.slimy.Slimy

depend: [FeatherBoard]
softdepend: [Multiverse-core]

commands:
  slimy:
    description: test
    aliases: [slime, s]